### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by zhouliang-yu** [liangxinedu/MDAM#2]
hey, @liangxinedu 
thank you for sharing your code.
I tried to download your pretrian model by 
```shell
 bash eval.sh download
```
but it doesn't work:
the error shows like this:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb8653ff760>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CL7KZHlnKVlGG2GImxcdqSbT_-Gs7UgX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8653ff760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_pretrained_models.py", line 37, in <module>
    download_file_from_google_drive(file_id, destination)
  File "download_pretrained_models.py", line 9, in download_file_from_google_drive
    response = session.get(URL, params = { 'id' : id }, stream = True)
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/zouliang/miniconda3/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1CL7KZHlnKVlGG2GImxcdqSbT_-Gs7UgX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8653ff760>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
unzip:  cannot find or open pretrained.zip, pretrained.zip.zip or pretrained.zip.ZIP.
```
so can you provide a new link to download the pretrained model?
Thx so much!

**Comment by liangxinedu** [comment]
Hi Zhouliang Yu,

Thank you for your interest in our work. Could you check if you have access
to the following links? The command `bash eval.sh download` just download
the models from these links.

https://drive
.google.com/file/d/1T-B8XKXz-yHRRiCCix0beYRq_Kk7bcV_/view?usp=sharing
https://drive
.google.com/file/d/1SgEgck_352gS7x-UIKhP1HekNMMXtREC/view?usp=sharing
https://drive
.google.com/file/d/1GtfXQtkCRZYvoYlDUd-f8UYqAO6XMnBU/view?usp=sharing

Best wishes,
Liang

Zhouliang Yu ***@***.***> 于2022年8月5日周五 19:08写道：

**Comment by zhouliang-yu** [comment]
Thank you @liangxinedu, could you pls also share the pretrained model of other cop: op, pctsp, and sdvrp? Since I can't find them on the above links.
Thx again for your effort!

**Comment by liangxinedu** [comment]
Dear Zhouliang Yu,

Sorry that I sent the links for another work of ours. Here is the link for
pretrained MDAM models.

https://drive.google.com/file/d/1CL7KZHlnKVlGG2GImxcdqSbT_-Gs7UgX/view?usp=sharing

Best wishes,
Liang


Zhouliang Yu ***@***.***> 于2022年8月5日周五 23:31写道：

**Comment by zhouliang-yu** [comment]
thx so much
